sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

install:
  - composer self-update

before_script:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit -c app/ --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  slack:
    rooms:
      - stefanius:V64KfmqnpFtzsYuWfHI65Clg#travis
