services:
    stef_simple_cms.contact_manager:
        class: Stef\GastouderMarjoleinBundle\Manager\ContactManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.entity_mapper:
        class: Stef\SimpleCmsBundle\EntityMapper\Mapper
        calls:
            - [addNewMapping, ["News", "StefSimpleCmsBundle", "Stef\SimpleCmsBundle\Entity", "@stef_simple_cms.news_manager"]]
            - [addNewMapping, ["Page", "StefSimpleCmsBundle", "Stef\SimpleCmsBundle\Entity", "@stef_simple_cms.page_manager"]]
            - [addNewMapping, ["Contact", "StefGastouderMarjoleinBundle", "Stef\GastouderMarjoleinBundle\Entity", "@stef_simple_cms.contact_manager"]]
