imports:
  - { resource: config_dev.yml }

framework:
  test: ~
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true
  session:
    storage_id: session.storage.mock_file
  profiler:
    collect: false

web_profiler:
  toolbar: false
  intercept_redirects: false

assetic:
  use_controller: true

swiftmailer:
  disable_delivery: true

monolog:
  handlers:
    main:
      type:     stream
      path:     %kernel.logs_dir%/%kernel.environment%.log
      level:    debug

doctrine:
  dbal:
    driver:  %database_driver_test%
    dbname:  %database_name%_test
    path:    %kernel.root_dir%/sqlite.db
    logging: %kernel.debug%